name: alking_pro
description: Alking Pro Trading Bot
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.0
  device_info_plus: ^9.1.0
  webview_flutter: ^4.4.0   # نرجع للإصدار الجديد

flutter:
  uses-material-design: true
